#!/bin/bash

# Fail on error.
set -e -x

# To install, make a link to these files in your home directory:
ln -s ~/dotfiles/nhdaly/zshrc.nhdaly ~/.zshrc && \
ln -s ~/dotfiles/nhdaly/vimrc.nhdaly ~/.vimrc && \
ln -s ~/dotfiles/nhdaly/vim ~/.vim && \
ln -s ~/dotfiles/nhdaly/tmux.conf.nhdaly ~/.tmux.conf && \
ln -s ~/dotfiles/nhdaly/gitignore.nhdaly ~/.gitignore && \
ln -s ~/dotfiles/nhdaly/atom ~/.atom && \
ln -s ~/dotfiles/nhdaly/juliarc.nhdaly.jl ~/.juliarc.jl && \
mkdir -p ~/.julia/config/ && \
ln -s ~/dotfiles/nhdaly/juliarc.nhdaly.jl ~/.julia/config/startup.jl && \
ln -s ~/dotfiles/nhdaly/iterm2_shell_integration.zsh ~/.iterm2_shell_integration.zsh || \
(echo "
Failed to install. If you're confident about it, you can erase those
pre-existing files with these commands:
rm -rf ~/.vim
rm ~/.vimrc
rm ~/.zshrc
rm ~/.tmux.conf
rm ~/.gitignore
rm -rf ~/.atom
rm ~/.juliarc.jl
rm -rf ~/.julia/config
rm ~/.iterm2_shell_integration.zsh
" && exit 1)

# Set up global gitintore file
git config --global core.excludesfile ~/.gitignore

# Also you'll need to install Antigen, our zsh package manager:
mkdir -p ~/bin
stat ~/bin/antigen/antigen.zsh || git clone https://github.com/zsh-users/antigen.git ~/bin/antigen
(cd ~/bin/antigen && git checkout v1.2.1)  # I had issues with the latest version of antigen.

# And Vundle:
stat ~/.vim/bundle/Vundle.vim/README.md || git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim +PluginInstall +qall

# And Tmux Plugin Manager:
stat ~/.tmux/plugins/tpm || git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# Then make zsh your default shell!
echo $SHELL | grep zsh | wc -l | ~/dotfiles/nhdaly/scripts/math-eval-bool-expr "== 1" || chsh -s /bin/zsh

# ---- Install conda for Python stuff: ----
curl -o ~/Downloads/Miniconda3-latest-MacOSX-x86_64.sh https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh && bash ~/Downloads/Miniconda3-latest-MacOSX-x86_64.sh

# Miniconda creates a .bash_profile, but we use bashrc:
cat /Users/nathan.daly/.bash_profile >> ~/.bashrc && rm ~/.bash_profile
source ~/.bashrc

conda update pip

# Install Powerline Fonts && tmux powerline-status
git clone https://github.com/powerline/fonts.git --depth=1 &&  (cd fonts; ./install.sh)  && rm -rf fonts
pip install powerline-status


# Install Homebrew
echo "Install homebrew: https://brew.sh/"
echo "Then install brew packages:"
echo "./INSTALL.brew"



# installed tools
# urlview  # (brew install urlview)

